obj-$(CONFIG_MT7601U)	+= mt7601u/
ifeq ($(CONFIG_MT76X3_OLD),y)
obj-$(CONFIG_MT76X3_AP) += mt76x3_ap_old/
else
obj-$(CONFIG_MT76X3_AP) += mt76x3_ap/
endif
ifeq ($(CONFIG_MT76X2_OLD),y)
obj-$(CONFIG_MT76X2_AP) += mt76x2_ap_old/
else
obj-$(CONFIG_MT76X2_AP) += mt76x2_ap/
endif
obj-$(CONFIG_MT7615_AP) += mt7615_ap/
obj-$(CONFIG_MT7915_AP) += mt7915_ap/
